### ISSUE TITLE
Guides pour le développement d'applications Android et IOS

### ISSUE THREAD

**Issue by kantoche** [DISIC/referentiel-mobile-tactile#1]
Bonjour,

A l'occasion du séminaire AccessiWeb du 4 décembre dernier avait été annoncée la publication prochaine par la DINSIC de deux guides sur le développement d’applications Android et IOS. Qu'en est-il ce travail ? 

Merci pour votre réponse.

**Comment by philippeBron** [comment]
Bonjour,

En effet, ces ressources sont disponibles dans le dépôt [Guide de développement d'applications mobiles accessibles avec les API Android et iOS](https://github.com/DISIC/guide-mobile_app_dev_natif).
Il existe également un [Guide de développement d'applications mobiles hybrides accessibles avec Ionic et OnsenUI](https://github.com/DISIC/guide-mobile_app_dev_hybride) qui pourra peut être également vous intéresser.

En espérant que cela réponde à votre question.
